### ISSUE TITLE
creating new attributes in data mode

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#1123]
According to [NetCDF user guide](https://www.unidata.ucar.edu/software/netcdf/docs/group__attributes.html#gab1089956b01ce5b40da6ace82a2d3b30) on creating new attributes, quoted below, I expect NC_ENOTINDEFINE when adding a new attribute in data mode, but got NC_NOERR instead. The short test program given below can reproduce the problem. Note this happens for NetCDF-4 files only. For classic files, NC_ENOTINDEFINE is returned as expected. I am testing it against 4.6.1 and master branch.
> If this attribute is new, or if the space required to store the attribute is greater than before, the netCDF dataset must be in define mode.

```
% cat attr_indata.c
#include <stdio.h>
#include <netcdf.h>

#define CHECK_ERR { \
    if (err != NC_NOERR) { \
        nerrs++; \
        printf("Error at line %d in %s: (%s)\n", \
        __LINE__,__FILE__,nc_strerror(err)); \
    } \
}

int main(int argc, char **argv) {
    int err, nerrs=0, ncid, cmode, varid, buf[2];

    cmode = NC_CLOBBER | NC_NETCDF4;
    err = nc_create("testfile.nc", cmode, &ncid); CHECK_ERR
    err = nc_def_var(ncid, "var", NC_INT, 0, NULL, &varid); CHECK_ERR
    err = nc_put_att_int(ncid, varid, "var_attr", NC_INT, 1, buf); CHECK_ERR 
    err = nc_enddef(ncid); CHECK_ERR

    err = nc_put_att_int(ncid, varid, "var_attr_new", NC_INT, 1, buf);
    if (err != NC_ENOTINDEFINE) {
        printf("Error on creating new attribute in data mode: expecting NC_ENOTINDEFINE but got %d\n",err);
        nerrs++;
    }
    err = nc_close(ncid); CHECK_ERR
    return (nerrs>0);
}
```

**Comment by DennisHeimbigner** [comment]
I suspect that this is an error in the documentation. I recall seeing code that for netcdf-4
explicitly does a redef if the file is not in def mode. However, for netcdf4-classic format,
this should not happen because it attempts to simulate the netcdf classic behavior.

**Comment by edhartnett** [comment]
@DennisHeimbigner 100% correct.

**Comment by edhartnett** [comment]
I have fixed it in my current branch ejh_hdf5_sep_next_2 so that will make its way into master in a few weeks.

**Comment by wkliao** [comment]
This is another inconsistency between NetCDF-4 extended and classic formats. What about calling def_dim and def_var APIs in data mode for NetCDF-4 formats? Are they allowed?

**Comment by edhartnett** [comment]
Yes, it is allowed to define a var or dim in data mode. In such a case, netcdf-4 helpfully calls enddef, makes the metadata change, and then calls redef to put the file back in data mode.

There are many differences between netCDF-4 and classic formats. That is the reason for NC_CLASSIC_MODEL. If you use that with nc_create, then anything that won't work in the classic model will be disallowed. With NC_CLASSIC_MODEL netCDF-4 passes the exhaustive tests in nc_test.

But HDF5 removes many of the restrictions. In the classic format, all metadata is in the header. So netCDF must know when you are done with metadata and ready to write data. And adding to the metadata is a big deal. With HDF5 this is not the case. You can add an attribute to the end of the file. Since the metadata are scattered throughout the file, they don't have to be defined before you start writing data.
