### ISSUE TITLE
Name conflict with the libhdf4

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#1150]
re: e-support issue KJJ-291289

Apparently the symbol NC_check_id in the netcdf-c library
causes a conflict with the same symbol being defined in libhdf4.
If libhdf4 is compiled with the --disable-netcdf flag, then this problem
goes away.

Doing a rename in the netcdf-c library apparently would affect some 30 files.
Not happy doing that.
The alternative is this hack:
1. modify configure.ac to check libhdf4 to see if NC_check_id is defined.
2. If defined, then print an error and fail. The error will indicate that
    the hdf4 library needs to be recompiled with --disable-netcdf.

Any preferences?

**Comment by edhartnett** [comment]
I believe hdf4 must be built with disable-hdf4 in any case, to work with netcdf.

How did you discover the conflict?

**Comment by edhartnett** [comment]
OK, I took a deeper look.

Indeed the configure.ac does not check that HDF4 was built with --disable-netcdf. And it should check that.

Even if this one function were re-named, the HDF4 link would still fail, because without --disable-netcdf, HDF4 includes all the netCDF classic public functions. So we can't link with that.

Therefore I agree that configure.ac should ensure that --disable-netcdf was used with HDF4. I will be happy to do this. I will put up a PR in a bit...

**Comment by BigTuna94** [comment]
I'm the one that originally reported this issue. I just wanted to add that the specific instance that I'm dealing with this issue is in an application that needs to link netCDF4 as well as the hdf-eos library which requires hdf4 compiled without the --disable-netcdf flag. 

I'm aware that the NC_check_id function is called across many files, but in my testing I had no issues renaming the function and changing calls to it. Please let me know if there is another reason that this fix isn't desirable.

**Comment by edhartnett** [comment]
And we're there no other conflicts?

**Comment by DennisHeimbigner** [comment]
The fact that hdf-eos requires --enable-netcdf in the hdf4 library is very odd.
It implies that hdf-eos requires some netcdf functions for which the hdf4 version's
semantics are different than those of the netcdf-c library. Can you identify
an example? Or equivalently, what goes wrong with hdf-eos when the hdf4 library
is compiled with --disable-netcdf?

**Comment by BigTuna94** [comment]
Sorry, I was mistaken. The library that was requiring --enable-netcdf was a different internal library that we use which is quite old. As it turns out, this library just exposed the issue I found when linking hdf4 built with --enable-netcdf and netcdf4. Because of this, I agree that your change is the correct solution. I apologize for the added confusion.
