### ISSUE TITLE
Not checking for curl.h in configure.ac

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#1152]
While working on #1150 I found this problem. On a machine without curl, the build fails like this:

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -I../libsrc4 -I/home/ed/local/hdf5-1.10.3/include -I/home/ed/local/hdf-4.2.13/include -MT libdap4_la-d4crc32.lo -MD -MP -MF .deps/libdap4_la-d4crc32.Tpo -c d4crc32.c  -fPIC -DPIC -o .libs/libdap4_la-d4crc32.o
In file included from d4crc32.c:43:0:
d4includes.h:19:10: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

I will combine this with the HDF4 configure fixes and put up a PR shortly...

**Comment by edhartnett** [comment]
OK, one problem here is that the configure script is trying to be too clever.

The convention is that if you ask for something to be built, and it is not possible, the configure will error out. It should not just change options for you. 

So right now, the build tries to build dap, but if curl is not present, it turns dap off. That may seem like a good idea, but it's not. A better idea is to error out and force the user to confront the issue. Either they need to install curl, or else build with --disable-dap. This decision should not be made by the configure script.

**Comment by DennisHeimbigner** [comment]
I recall this issue from some months ago. I guess I thought that the pr for it
had done a comprehensive set of changes to configure.ac to have the failure
behavior. Or did that pr never get merged?

**Comment by DennisHeimbigner** [comment]
I remember one more problem with this. In order to make this work in general, it
was necessary to know if the ./configure command explicitly set, for example, --enable-dap,
then an error should be reported. However if dap was defaulted, then it should just disable
dap without causing ./configure to fail. This was to protect naive users who did a default
build. 

This caused a problem with cmake, because it was not possible using option() to tell
if the cmake command explicitly set an option or was defaulting. As I recall,
Wei-king solved this by using some other mechanism.

**Comment by wkliao** [comment]
In my opinion, configure should error out if the user explicitly enables or disables a feature, but configure could not support it. Otherwise, configure can decide for the user (i.e. auto mode used in PnetCDF and MPICH). NetCDF prints all the settings on screen at the end of configure and users can also use utility nc-config to check all the features enabled/disabled.

**Comment by DennisHeimbigner** [comment]
>For autoconf there is a clear convention which we are attempting to outsmart. 
The question that has to be decided is exactly the default(==auto?) case.
If the user says nothing about dap, and libcurl is not accessible,
then what should be reported to the user?
1. fail
2. disable dap, give a warning, and continue.
Which of these is the convention you refer to?

**Comment by edhartnett** [comment]
@wkliao installers do not run `./configure --help` and read all the output to see if any conventions are not being followed. Nor do they read the documentation before installing. 

@DennisHeimbigner the build should fail without curl. User then can easily --disable-dap or install curl, whatever they wish. Failure message can offer them that choice. This is the simple and correct answer.

If I do:

`./configure && sudo make install
`

It should either build correctly with all defaults, or error out in configure. It should not tell me it succeeded when it actually could not build everything. 

Recall that many science users will have to ask sysadmins to install netcdf. The sysadmin will do so, and then the scientist will expect it to work. If not, that leads to back and forth with the sysadmin to try and figure out what is happening, wasting everyone's time. Printing a warning in the thousands of lines of output certainly won't be noticed. 

We do not need to figure out a new and better way to use autoconf - we need to use it in the way everyone expects. This will be less work for us, less confusion for users, and less support for the netCDF team and all the sysadmins who need to install it for their users.
