### ISSUE TITLE
cmake seems to insists on having HDF5 built with CMake

### ISSUE THREAD

**Issue by doutriaux1** [Unidata/netcdf-c#123]
```
 CMake Error at /usr/local/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
   Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS)
 Call Stack (most recent call first):
   /usr/local/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
   /usr/local/share/cmake-3.3/Modules/FindHDF5.cmake:375 (find_package_handle_standard_args)
   CMakeLists.txt:480 (FIND_PACKAGE)
```

**Comment by WardF** [comment]
You *should* be able to specify non-cmake-built hdf5 libraries with the following options:

* -DHDF5_LIB=/path/to/hdf5.lib
* -DHDF5_HL_LIB=/path/to/hdf5_hl.lib
* -DHDF5_INCLUDE_DIR=/path/to/hdf5/include

I'm bringing up an environment to test this, however, since it's been a while since I added those options and some of the cmake underpinnings have changed a little.  I'll follow up here after I've had a chance to look.

**Comment by WardF** [comment]
Further reference here (but as alluded to above, I need to verify that it still holds true and either correct it or update the FAQ):  http://www.unidata.ucar.edu/software/netcdf/docs/ncFAQ.html#cmake_faq

**Comment by WardF** [comment]
So, two things.  First, cmake on my local machine can automatically detect non-cmake-built libhdf5 without any problems.  If I install hdf5 in a non-standard location, I'm able to specify them directly, using the options listed above.  For example, when installed into my home directory in `local-hdf5/`, 

    $ cmake .. -DHDF5_LIB=~/local-hdf5/lib/libhdf5.so -DHDF5_HL_LIB=~/local-hdf5/lib/libhdf5_hl.so -DHDF5_INCLUDE_DIR=~/local-hdf5/include

succeeds.

Since this isn't a cmake or netcdf issue directly, I'm going to close out this issue as there's nothing I can do about it on my end.

**Comment by doutriaux1** [comment]
thanks, I was thrown off by the HDF5_DIR CMake variable, sorry about the noise.
