### ISSUE TITLE
Previously valid netCDF endpoint returns "NetCDF: Not a valid data type or _FillValue type mismatch" with latest netcdf-c

### ISSUE THREAD

**Issue by ocefpaf** [Unidata/netcdf-c#1299]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [X] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [X] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [X] [cmake](https://github.com/conda-forge/libnetcdf-feedstock/tree/master/recipe)
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [X] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue

Accessing the URL below results in

```
NetCDF: Not a valid data type or _FillValue type mismatch
```
with `netcdf 4.6.2` but works just fine with `netcdf 4.6.1`.

Not sure if the Dataset is at fault and the previous netcdf-c version was too forgiving, or if something is amiss with my build of netcdf-c 4.6.2.

### Steps to reproduce the behavior

```shell
ncdump -h https://data.ioos.us/thredds/dodsC/deployments/rutgers/ru29-20150623T1046/ru29-20150623T1046.nc3.nc
```

**Comment by DennisHeimbigner** [comment]
The problem is that the server appears to be generating a fillvalue whose type is different
than the associated variable.
One example is the variable 'conductivity_qc' whose type is Byte, but
whose _FillValue type appears to be Int16.
We strongly recommend that you contact the server owners and have them
fix the mismatch.
However, having seen this before, we have provided a workaround.
If you suffix the URL with the string '#fillmismatch', then is should work ok.
So, the URL passed to ncdump would look like this:
````
ncdump -h 'https://data.ioos.us/thredds/dodsC/deployments/rutgers/ru29-20150623T1046/ru29-20150623T1046.nc3.nc#fillmismatch'
````

**Comment by ocefpaf** [comment]
Thanks @DennisHeimbigner! I'll follow up with the data providers.
