### ISSUE TITLE
Improve OPeNDAP error message

### ISSUE THREAD

**Issue by dopplershift** [Unidata/netcdf-c#1316]
If we try to access a non-existent URL, a seriously unhelpful error message results:
```sh
>ncdump -h https://thredds-test.unidata.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190211/OR_ABI-L1b-RadF-M3C13_G17_s20190421530382_e20190421541160_c20190421541201.nc
ncdump: https://thredds-test.unidata.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190211/OR_ABI-L1b-RadF-M3C13_G17_s20190421530382_e20190421541160_c20190421541201.nc: https://thredds-test.unidata.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190211/OR_ABI-L1b-RadF-M3C13_G17_s20190421530382_e20190421541160_c20190421541201.nc: NetCDF: Not a valid data type or _FillValue type mismatch


>curl https://thredds-test.unidata.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190211/OR_ABI-L1b-RadF-M3C13_G17_s20190421530382_e20190421541160_c20190421541201.nc
Error {
    code = 400;
    message = "Unrecognized request";
};
```

It's possible this is specific to hitting the 404 page from TDS. Regardless, having the library yield the OPeNDAP equivalent of "File Not Found" or "Invalid File" would be so much more helpful.

**Comment by dopplershift** [comment]
Oh, I see now it's a 400, not a 404. Either way, I'd love a better error message. (Why this particular URL is even giving an error is a bug in TDS.)

**Comment by WardF** [comment]
@DennisHeimbigner is there an easy way to check the error code coming back?  I could dig into this if so.  I'm not sure if DAP is parsing error codes returned or if it's just checking for an error.

**Comment by lesserwhirls** [comment]
You want to add .dods after the .nc, as well as some constraint. So something like:

~~~bash
curl https://thredds.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190213/OR_ABI-L1b-RadF-M3C13_G17_s20190441600381_e20190441611159_c20190441611201.nc.dods?y[0:1:5423]
Dataset {
    Int16 y[y = 5424];
} satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190213/OR_ABI-L1b-RadF-M3C13_G17_s20190441600381_e20190441611159_c20190441611201.nc;
~~~

That said, the issue is **bigger than just the error message**, as `ncdump` on the url _works_ in 4.6.1, but _not_ 4.6.2.

So:

netcdf library version 4.6.2 of Dec 17 2018 19:20:47

~~~bash
ncdump -h https://thredds.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190213/OR_ABI-L1b-RadF-M3C13_G17_s20190441600381_e20190441611159_c20190441611201.nc
ncdump: https://thredds.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190213/OR_ABI-L1b-RadF-M3C13_G17_s20190441600381_e20190441611159_c20190441611201.nc: https://thredds.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190213/OR_ABI-L1b-RadF-M3C13_G17_s20190441600381_e20190441611159_c20190441611201.nc: NetCDF: Not a valid data type or _FillValue type mismatch
~~~

netcdf library version 4.6.1 of Jan 27 2019 11:38:15

~~~bash
ncdump -h https://thredds.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190213/OR_ABI-L1b-RadF-M3C13_G17_s20190441600381_e20190441611159_c20190441611201.nc | less
sarms@flip:$ ncdump -h https://thredds.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190213/OR_ABI-L1b-RadF-M3C13_G17_s20190441600381_e20190441611159_c20190441611201.nc
netcdf OR_ABI-L1b-RadF-M3C13_G17_s20190441600381_e20190441611159_c20190441611201 {
dimensions:
	band = 1 ;
	num_star_looks = 24 ;
	number_of_image_bounds = 2 ;
	number_of_time_bounds = 2 ;
	x = 5424 ;
	y = 5424 ;
<snip>
~~~

**Comment by WardF** [comment]
So, the `_FillType mismatch` error is *hasn't had coffee yet so recollection is hazy* a fix we introduced in 4.6.2 for behavior that was documented but not previously enforced.  Let me go back and dig through the PR's/Support emails to refresh my memory.

**Comment by WardF** [comment]
Ok, it looks like there was some work done to work around this change when using DAP: https://github.com/Unidata/netcdf-c/pull/1155

It clearly needs to be highlighted in the documentation.

**Comment by WardF** [comment]
I can confirm that, for me, the following command works

    $ ./ncdump -h [fillmismatch]https://thredds.ucar.edu/thredds/dodsC/satellite/goes17/GRB17/ABI/FullDisk/Channel13/20190213/OR_ABI-L1b-RadF-M3C13_G17_s20190441600381_e20190441611159_c20190441611201.nc

So perhaps this is a failure of documented DAP behavior, or at least indicates the need to highlight this new behavior.  Or, based on conversation in my office with @dopplershift just now, perhaps [fillmismatch] needs to be implicitly true when doing DAP operations.

**Comment by DennisHeimbigner** [comment]
Correct. The netcdf spec requires the type  of a _FillValue attribute to be
the same as the associated variable. We have started to enforce it.
However, if you suffix a url with '#fillmismatch', an attempt will be made
to forcibly convert the _FillValue value to the type of the variable.

**Comment by WardF** [comment]
Playing with the file locally, I do not get a mismatch error.  Sitting in a meeting at the moment, but surprised at the different behavior, unless I've already been told and just forgot, in which case ah, yes, I remember.

**Comment by DennisHeimbigner** [comment]
The problem may be that since DAP2 does not support signed byte, the converter
widens to int16 to store the _FillValue.

**Comment by DennisHeimbigner** [comment]
Ok, am testing fix now in the netcdf-c library.

**Comment by DennisHeimbigner** [comment]
Fixed as discussedd: see https://github.com/Unidata/netcdf-c/pull/1317

**Comment by DennisHeimbigner** [comment]
Fixed as discussedd: see https://github.com/Unidata/netcdf-c/pull/1317
