### ISSUE TITLE
Bring nc-config behavior in line with pkg-config behavior.

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#1360]
Follow-on to #1257.  The behavior of `nc-config` should be in-line with that of `pkg-config`, insofar as there being a method to get flags for linking statically vs. dynamically.

**Comment by Dave-Allured** [comment]
I suspect that the use of `nc-config --libs` among users is a lot more common than `pkg-config --libs`, because of preference in netcdf user documentation and other reasons.  Therefore it is likely that changing `nc-config --libs` behavior in exactly the same way will break many users' static builds.  Therefore I suggest two possible alternatives to reduce surprise breakage.

* Do not change `--libs`.  Instead add a new `nc-config` flag to signal shared rather than static build.  The new flag could be either a supplement to `--libs`, or a replacement.

* Or else, simply document that `pkg-config --libs` is now the preferred method for shared linking, and that it avoids [overlinking](https://wiki.openmandriva.org/en/Overlinking_issues_in_packaging).  Make no change at all to `nc-config`.  This is less work and would be fine with me.

**Comment by WardF** [comment]
I agree 100% that we shouldn't break existing workflows.  On the other hand, a side effect of the changes in #1324, the behavior of nc-config has been changed as of version `4.6.3`, with no complaints from any users.  I will be updating nc-config to have the --static flag, and will also figure out whether it should be on by default at this point.
