### ISSUE TITLE
Modify DAP2 tests to no longer use test.opendap.org

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#1451]
At least one test (ncdap_test/test_zero_len_var.sh) is using
the test.opendap.org server.  There might be others.
It might be better if all of these tests
were modified to use our remote test server.
re: https://github.com/Unidata/netcdf-c/issues/1449#event-2529286420

**Comment by xylar** [comment]
It seems like the test.opendap.org server has been down again for a few days.  We're trying to support more systems for `libnetcdf` on `conda-forge` but can't really make headway at the moment.  So we'd be keen to see the move away from test.opendap.org happen.

**Comment by DennisHeimbigner** [comment]
Have you contacted opendap support?
I hate to remove or tests that use the opendap
server because it checks that our code has not become
specific to our remotetest server. If this continues to'
be a problem, then we will have to talk to the opendap
people about it.

**Comment by xylar** [comment]
I'm contacting them now.  I saw the previous issue from Aug 2 and got the impression that this might be a frequent issue.

**Comment by xylar** [comment]
It seems like we (as a community) just need to ping them if we find the server to be down.  OpenDAP staff maybe don't necessarily notice when the server goes down. Here's what I just heard back:
> Should be up now.
> 
> Please don't hesitate to let us know if you find it down in the future.

**Comment by DennisHeimbigner** [comment]
My experience has been that their server is pretty reliable
and does not go down often.

**Comment by xylar** [comment]
Okay, that's very good to hear.

**Comment by Dave-Allured** [comment]
Suggestion.  Make DAP tests adaptive.  If remote opendap.org server is not responding, then fall back and complete the test suite using the Unidata test server.

Also provide an option, probably a configure option, to disable fallback, and require the opendap.org server.

This is because you have two competing objectives.  One is to make it easier for user builds to prove their DAP functionality, and reduce gratuitous test suite failures.  The other is as Dennis said earlier, "check that our code has not become specific to our remote test server".  Users do not usually care about this latter objective, I think.  Thus the default test behavior should be forgiving of single server failures.

**Comment by DennisHeimbigner** [comment]
Dave makes an excellent point about server failures. I will attempt to
modify our tests so that server failures warn but otherwise pretend
to succeed. This puts a burden on Unidata to detect such cases,
but will hide spurious failures from users.
