### ISSUE TITLE
Add a unit_test directory and put some unit tests in

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1458]
What we have for tests are system tests, i.e. tests that exercise the system functions. In doing so we (hope to) test all the code underneath. These tests all involve the external functions from netcdf.h.

One thing Russ and I discussed back in olden times was to also add some unit tests. That is, tests of netCDF internal functions. Back in olden times there were fewer internal functions, and we never got around to adding testing just for them. But now there are more internal functions, as the capabilities of the dispatch layer and libsrc4 have grown.

At the moment I would like to write tests for the code in nclistmgr.c and I don't really have a good place to put those tests.

So I suggest I add a unit_test directory. It will come first in the test order, and will contain unit tests for the code in libdispatch and elsewhere which is always built (i.e. for both classic and netcdf-4 builds.) I would then later add an unit_test4 for unit tests of code in libsrc4 that is only built in netcdf-4 builds.

There is a good reason to keep system tests and unit tests separate. By monitoring the code coverage of system tests, we can find code that is not really used. However, unit tests obscure this, since they test the internal functions. So those functions always show up as tested code, even if they are never actually used anywhere in the code base. I will add a configure option to disable unit tests, so I can measure code coverage properly.

@WardF and @DennisHeimbigner does this seem OK?

**Comment by DennisHeimbigner** [comment]
Actually, there are a few unit tests scattered in various directories: dap, for example.
One problem with them is that it is hard to run those tests using Visual
studio because the internal functions need to be exported using declspec.

**Comment by edhartnett** [comment]
I suggest that the unit tests only be run in the autotools build. Then,
windows will just ignore them.

**Comment by DennisHeimbigner** [comment]
It is not obvious to me that unit tests should be separate from
integration tests, especially for dispatch specific test directories
like ncdap_tests and dap4_tests and (soon) zarr_tests.

**Comment by edhartnett** [comment]
They are separate because:
1 - they are used across dispatch layers
2 - they are not public functions
3 - they should be turned off for code coverage checking

For the testing of each dispatch layer's public API we should continue to add a test directory for each dispatch layer (ex. zarr_test).

**Comment by DennisHeimbigner** [comment]
What about dispatch specific unit tests?

**Comment by edhartnett** [comment]
If you mean testing of libdispatch, that would be unit tests, because all the public functions in libdispatch are already tested in nc_test/nc_test4, etc.

**Comment by DennisHeimbigner** [comment]
No. For example, the zarr_tests has unit tests for testing
chunking functionality and internal lowest level storage functions.
These  cannot be tested directly thru the netcdf API. Currently,
these unit tests are in zarr_test along with integrations tests.

**Comment by DennisHeimbigner** [comment]
In any case, I think what you propose is reasonable. For me
the only issue is whether the unit test dir should have all unit tests
or just those that are independent of any specific dispatcher.
I can see arguments both ways. Perhaps Ward has a comment.

**Comment by edhartnett** [comment]
OK, great. I have a PR up for this, #1460

**Comment by WardF** [comment]
Back from being out of the office for the past week.  I agree it's broadly reasonable, although I see Dennis' point about whether unit tests should be in their own directory universally, or only if there is no other neat bin for them to sit in.  I'm tempted to say lets keep unit tests in their own directory, we can always move them around if there is a reason to.

I don't think that having unit tests only run in autotools is a good idea, however.   I can think of some mechanical solutions to this, but it also feels like a problem (unit testing internal functions in cross-platform code bases in Visual Studio) that other folk will have encountered.

I'm wading through a week of email.  Let me take a look at that.  To summarize, I think it's a great idea, thank you very much Ed.  I'd like to figure out how to add these tests to cmake as well, because it is perfectly reasonable for us to expect bugs which may only manifest in a platform specific manner, and I'd sure like to catch those when they happen.

**Comment by edhartnett** [comment]
I have been thinking about it and I believe all tests that do not involve public functions should go in unit_test.

The reason is that we can turn of unit tests, and then run the rest of the tests, and we will find any dead code. (That is, code that is not run by any of the public functions.)

Agree that it would be nice to get this working for cmake too. I will leave that to you Ward. ;-)

**Comment by WardF** [comment]
Sounds good.  We are also overdue on releases, so I'm flagging these for 4.7.2 so that I can get 4.7.1 out the door asap, followed by the Fortran and C++ releases. Thanks!

**Comment by edhartnett** [comment]
Well this is actually part of #1457 and it would be great if that could be part of the 4.7.1 release. I will probably have a final fix for #1457 tomorrow...

**Comment by WardF** [comment]
It's unlikely I'll have the cmake half of this in by tomorrow, but I'll take a look once I get caught up on emails and non-PR stuff.  The 4.7.2 release will come fairly quickly, however, fwiw.  We shall see.

**Comment by edhartnett** [comment]
OK, well if you could merge this PR, it would help. It's perfectly safe for 4.7.1 and required for #1457.

**Comment by edhartnett** [comment]
We have the unit_test directory and its working, so I believe this issue can be closed.

**Comment by edwardhartnett** [comment]
OK, I see this issue was still open because these unit tests are not yet working in Cmake. I will take a stab at that, since I am trying to learn more about cmake builds...

**Comment by edhartnett** [comment]
I do not believe we want to run unit tests on windows.

The reason: the unit tests are specifically for internal functions. In order for them to work in Windows, they need to be declared with EXTERNL, which will make them publicly exposed functions in the library. We don't want that.

So I have added all the unit tests to the CMake build, but left the part where the unit_test directory is not run on Windows. I've added a comment to the CMakeLists.txt file describing why.
