### ISSUE TITLE
fortran flags in nc-config

### ISSUE THREAD

**Issue by Try2Code** [Unidata/netcdf-c#1544]
hi!

this is just a question regarding Fortran and C. In the current release 4.7.2 the nc-config has several fortran related information:

```
  --has-fortran   -> yes
  --fc            -> gfortran
  --fflags        -> -I/usr/include
  --flibs         -> -L/usr/lib -lnetcdff -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -lnetcdf -lnetcdf -ldl -lm
  --has-f90       -> 
  --has-f03       -> yes
```

why is this the case? netcdf-fortran has its own ```nf-config``` script and netcdf_c has not relation to fortran, hasn't it?

thx in advance
try2

**Comment by WardF** [comment]
@Try2Code This is legacy code that predates `4.7.2` by quite a bit; I suspect it harkens back to when `libnetcdf` was a monolithic library providing the Fortran/C++/C interfaces from a single library.  When the interfaces were separated out, I surmise that this was done so that workflows that queried `nc-config` wouldn't need to be changed to also query `nf-config`, etc.  

Thanks, I hope this answers the question!

**Comment by edwardhartnett** [comment]
I wonder however if it is correct information?

If I build netcdf-c then build netcdf-fortran, how does netcdf-c know where I will put netcdf-fortran?

**Comment by WardF** [comment]
It invokes `nf-config` dynamically if found, it isn't baked in when nc-config is generated from nc-config.in.

**Comment by WardF** [comment]
````

nfconf=$(which nf-config 2>/dev/null)

if [ -f "$nfconf" ]; then
  has_fortran="yes"
  fc=`nf-config --fc`
  fflags=`nf-config --fflags`
  flibs=`nf-config --flibs`
  has_f90=`nf-config --has-f90`
  has_f03=`nf-config --has-f03`
fi

````

**Comment by Try2Code** [comment]
thx for clarification. So with 4.7.2 this is planed to be removed?

**Comment by WardF** [comment]
@Try2Code No, no plans to remove this.
