### ISSUE TITLE
Provide a way to do jpeg compression

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1549]
Jpeg compression is great. All the kids are using it. So it would be great if it would be well supported in netCDF-4.

With @DennisHeimbigner filter work, this should be straightforward. 

This is part of #1545

**Comment by dopplershift** [comment]
JPEG or JPEG2K? I'm only aware of the latter being used for GRIB.

**Comment by edwardhartnett** [comment]
JPEG2K

**Comment by dopplershift** [comment]
JPEG2K does seem to be popular. The library implementations of this compression are also complex and can be challenging to build. conda-forge only recently got windows builds for Jasper (with the 2.x series). OpenJPEG seems to be better, but for some reason I only recently learned of its existence--which makes me wonder about it.

On the Java side, there's JJ2000--which we seem to be the only maintainers of, which should send a shiver of fear down everyone's spine. That code was causing an internal compiler error in javac for Java 1.8 when I first got here.

I'm not trying to say for certain "don't do it". Just that the phrase
>  this should be straightforward.
is a terrifying statement for me in regard to JPEG2K, and fills me with a sense of dread with regards to potential support issues.

I have strong opinions about JPEG2K, because of my experience on the netCDF-java side, and I'm especially bear-ish on the prospect of promoting its use for a data format that's supposed to have strong guarantees on its suitability for data archival. We already have one large, complicated storage format underlying netCDF. :wink:

**Comment by edwardhartnett** [comment]
This is what is used by GRIB, the greatest competitor to netCDF and a data format we should all want to see in the dustbin of history.

So I am sure we can do better at this than GRIB, despite the difficulties.

**Comment by epourmal** [comment]
Please see [JPEG HDF5 filter ](https://bitbucket.hdfgroup.org/projects/TEST/repos/hdf5_plugins/browse/JPEG) supported by Mark Rivers <rivers@cars.uchicago.edu>

**Comment by edwardhartnett** [comment]
I believe this issue will best be pursued through the community codec repo project: Further discussion should take place there: https://github.com/ccr/ccr

I will close this issue.
