### ISSUE TITLE
NetCDF: HDF error

### ISSUE THREAD

**Issue by renato2099** [Unidata/netcdf-c#1551]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue
netcdf-c v4.7.3 and also master
using hdf5-1.10.5

* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
Ubuntu 16.04
CXX=clang++-7.0 CC=clang-7.0
For compiling HDF5 I used:
`CXX=clang++-7.0 CC=clang-7.0 cmake -DCMAKE_INSTALL_PREFIX=/opt/hdf5 .. `
For compiling netcdf-c I used:
`
CXX=clang++-7.0 CC=clang-7.0 \
    cmake \
        -DCMAKE_INSTALL_PREFIX=/opt/netcdf-c \
        -DENABLE_PARALLEL_TESTS=OFF \
        -DENABLE_BYTERANGE=ON \
        ..
`
There was no problem at compilation time. Everything build successfully. 

* a description of the issue with the steps needed to reproduce it
ncdump 3B.nc4

the test file can be downloaded from here 
http://tpch-rmm-fk.s3.eu-central-1.amazonaws.com/3B.nc4

If you have a general question about the software, please view our [Suggested Support Process](https://www.unidata.ucar.edu/support/#process).

The problem is that I cannot read an hdf5 file that was converted into nc4. I always get the following error which I don't know where to start looking from:

`
 precipitationQualityIndex =
NetCDF: HDF error
Location: file /tmp/netcdf-c/ncdump/vardata.c; line 478
  root@fc569074bc6c:/opt/netcdf-c/bin# vim /tmp/netcdf-c/ncdump/vardata.c 
`
Any pointers or suggestions are highly appreciated.

**Comment by edwardhartnett** [comment]
Can you open the file with a C program? (That is, without ncdump).

Try a program that does something like this:

```
if (nc_open(FILE, 0, &ncid)) ERR;
if (nc_close(ncid)) ERR;
```

Make sure you check the return codes. Also, upload a copy of the file.

Did this work with previous versions of netCDF?

Also you say you converted a HDF5 into NC4? How exactly? You should be able to read the original HDF5 file directly with netCDF, with no conversion necessary.

**Comment by Dave-Allured** [comment]
I can read the file **3B.nc4** successfully and completely with **ncdump-4.7.3** and **HDF5-1.10.5** on **Mac OS 10.14.6** (Mojave).  However, I find two strange things about this file.

* The file time stamp is October 15.  This pre-dates the **netcdf-c-4.7.3** release.  Therefore I assume that your problem is specifically with **ncdump-4.7.3**, and not the nccopy version that made this file.

* Chunk sizes are 1024 x 1024.  This is large enough to exceed the default chunk cache, causing ncdump to run absurdly slowly when displaying data arrays.  This is a known problem, but it is a very different problem than your HDF error.

Do you have any HDF environment variables set?  Please show the result of `env | grep -i hdf`.  Also, sigh, you might as well show `ldd` on the full path of your ncdump executable.

I think the main problem is in your 4.7.3 ncdump and library.  I suggest focussing on that, not the test file.

**Comment by Dave-Allured** [comment]
Also please show the last line of `ncdump` with no file or other arguments.  This shows another clue about your `ncdump` version.

**Comment by renato2099** [comment]
Thanks for the prompt reply @edwardhartnett !
I found the problem with some debugging. The problem was that on my installation I removed zlib library, and although everything compiled properly, I would just get that error.
I fixed the problem by making hdf5 to enable support for zlib

` CXX=clang++-7.0 CC=clang-7.0 cmake -DCMAKE_INSTALL_PREFIX=/opt/hdf5 -DHDF5_ENABLE_Z_LIB_SUPPORT=ON ..`

I think the HDF library should have this option enabled by default as people might use it anywhere and disable it otherwise. Thanks anyway!
