### ISSUE TITLE
pkgconfigdir should be set by autoconf macro, not in netcdf-c Makefile.am

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1699]
This issue arises when building NCEPLIBS (https://github.com/NOAA-EMC/NCEPLIBS), a key component in the GFS.

The NCEPLIBS build system (CMake based) uses pkgconfig to learn about netCDF. No doubt this is a common practice. Has anyone raised this issue before?

In order for pkgconfig to find the netcdf.pc file, I had to add the directory to environment var PKG_CONFIG_PATH before the build could find the netCDF pkgconfig files. (For pkgconfig docs see https://linux.die.net/man/1/pkg-config.)

Looking into this with my assistant Mr. Google, I learn that this is a common problem. As a result, there is an autoconf macro called PKG_INSTALLDIR (See http://manpages.ubuntu.com/manpages/cosmic/man7/pkg.m4.7.html and for an example of use see https://stackoverflow.com/questions/28997618/installing-pkg-config-files-to-proper-path-on-centos-with-automake).

In CMake there is FindPkgConfig (https://cmake.org/cmake/help/latest/module/FindPkgConfig.html?highlight=pkgconfig) but I can't see that it tells what install directory to use for pkgconfig.

@WardF do you know a way to set the pkgconfig installdir in CMake?

The problem of course is how to handle cases where the user does not have the authority to write to the directory where the system looks for pkgconfig files. Then we must default back to using our current locations.

In this way users doing a system-wide install of netCDF will get pkgconfig working everywhere automatically. Those installing to a personal directory will have to add to environmental variable PKG_CONFIG_PATH.

**Comment by WardF** [comment]
@edwardhartnett This issue has not been raised before that I can recall, but that only means so much.  But no, I don't think it has.  Let me take a look at what is generated by FindPkgConfig and follow up.  Looking now.

**Comment by WardF** [comment]
So CMake uses [CMAKE_PREFIX_PATH](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html#variable:CMAKE_PREFIX_PATH) as a catch-all list of directories when searching for libraries, programs, files, etc.  When libraries and files are installed in a non-standard location, for example, I will specify 

    `-DCMAKE_PREFIX_PATH=/media/some/esoteric/path`

wherein the expected `lib/`, `bin/`, etc directories will be found.  I would expect CMake to use this information to also look for the netCDF pkgconfig files.  You can perhaps check this faster than I can, as it sounds like you have `NCEPLIBS` in front of you.  If you use `CMAKE_PREFIX_PATH` instead of `PKG_CONFIG_PATH`, does cmake find the netCDF pkgconfig files? 

If so, I see a couple options.  First, from the FindPkgConfig documentation, it looks like adding

`cmake_minimum_required(VERSION 3.1)` 

to the NCEPLIBS CMakeLists.txt file will set the `PKG_CONFIG_USES_CMAKE_PREFIX_PATH` variable to `True` by default, which should result in cmake using the value of `CMAKE_PREFIX_PATH`, which I *believe* (but need to look in to) defaults to `CMAKE_SYSTEM_PREFIX_PATH` if the user doesn't specify a value.  

Alternatively, if `NCEPLIBS` doesn't want to add a minimum-required cmake version, it can explicitly set `PKG_CONFIG_USE_CMAKE_PREFIX_PATH` to `True` in `CMakeLists.txt`.

**Comment by edwardhartnett** [comment]
The NOAA packages have the somewhat difficult:

`cmake_minimum_required(VERSION 3.12)
`

THis is far beyond what comes as default with Ubuntu, so one has to first build cmake before even starting to build NCEPLIBS. This is unfortunate but time will pass and 3.12 will be more common.

I will check the behavior of CMAKE_PREFIX_PATH as you suggest...
