### ISSUE TITLE
Missing constants for nc_def_var_szip

### ISSUE THREAD

**Issue by mjwoods** [Unidata/netcdf-c#1704]
The current online documentation for nc_def_var_szip mentions two constants, NC_SZIP_EC and NC_SZIP_NN. However, these constants are not defined in the public header files of netcdf-4.7.4 or the current master (1d2fca9813a). The builtin tests for netcdf are not detecting the problem because the constants are defined in nc_test4/tst_vars3.c .

**Comment by WardF** [comment]
Thanks @mjwoods I'll get this fixed.

**Comment by DennisHeimbigner** [comment]
These are defined in include/netcdf_filter.h, but have different names, probably
the names defined by hdf5 headers.

**Comment by edwardhartnett** [comment]
I believe that in the case of szip, they should be defined in netcdf.h, just as the zlib constants are.

Alternatively, can we include netcdf_filters.h in netcdf.h?

**Comment by DennisHeimbigner** [comment]
I have left the deflate constants in netcdf.h because it is always there when netcdf-4
is enabled. Szip is optional, so I am not sure that it should be in netcdf.h.
As for including netcdf_filters.h in netcdf.h, we have had this conversation
before with no agreement, so I am willing to have it again.
My argument is that the user includes netcdf.h and then includes secondary netcdf_xxx.h
headers for those features used by the client code. So the same argument applies, for me,
with respect to netcdf_parallel.h.
Anyone else have an opinion?

**Comment by edwardhartnett** [comment]
One difference with netcdf_parallel.h, and the reason it is in a separate file, is that it includes mpi.h, which will not be present for sequential builds.

Anyway, let's leave it as it is for the 4.9.0 release, and worry about it next time around. ;-)

For most of my NOAA users, it doesn't matter - they do everything in Fortran and never do anything in C. So netcdf-fortran will have to have an extra include, and that is no problem whatsoever. So for most users, this is a non-issue.

I will change my szip constants to match the netcdf_filter definitions, in the test code and in the documentation. This will be the fastest path forward for the next release...
