### ISSUE TITLE
What's the deal with fill value type mismatches?

### ISSUE THREAD

**Issue by edwardhartnett** [Unidata/netcdf-c#1766]
In some GFDL code that part of the NOAA model code, I'm seeing this error in their code:

`FATAL from PE     1: NetCDF: Not a valid data type or _FillValue type mismatch
`

I seem to remember that the library added checking for the type of _FillValue - is that correct? It seems that this GFDL code is setting _FillValue of incorrect type.

What version of netcdf was this check introduced in? I can't find any mention in the release notes.

**Comment by DennisHeimbigner** [comment]
This originally came from the users-guide (or maybe the spec), but
it specifically states that the type of the _FillValue attribute and the type
of the variable must be the same type.

We had fixed that for opendap to essentially drop that constraint
(assuming the two types are inter-convertible). I assume you are not
using opendap. You can spot the error in the file by doing the
type comparisons for each variable with an assigned _FillValue.

I am getting sick of this recurring issue and I propose we just
drop the constraint altogether. [Ward, any opinion?]

**Comment by edwardhartnett** [comment]
Well stand by, this may have nothing to do with fill value after all. Let me debug the FMS test and figure out what is going on.

So what I'm hearing is that the library itself does not complain about fill value, it's a dap thing?

**Comment by DennisHeimbigner** [comment]
Sorry, I was not clear. THe problem is that a  lot of opendap servers send metadata that the netcdf-c library converts to netcdf-3 but in a way that causes fillvalue mismatch.
So the error is actually in the netcdf-c library.
We have hacked only the opendap code to suppress this.
The mismatch error, can also occur in non-opendap data sources (including a regular .nc file) if whoever built the data source somehow created a _FillValue with a different type that its associated variable.
As I said, it has caused a lot of complaints.

**Comment by edwardhartnett** [comment]
OK, thanks for the explanation. This is not what is happening with FMS, so the problem is elsewhere. I will close this issue.
