### ISSUE TITLE
8-byte integer global attribute crash in netcdf 4.7.4?

### ISSUE THREAD

**Issue by menzel-gfdl** [Unidata/netcdf-c#1807]
With netcdf 4.7.4, the code included below crashes with:

```
NetCDF: Not a valid data type or _FillValue type mismatch
```

This was built with ifort 19.1.2.254.  The code runs with older versions of netCDF.  Is there
some kind of issue with 8-byte integer global attributes?  I've tried a pure C version too, and also get this error.

```fortran
program main
use, intrinsic :: iso_fortran_env, only: error_unit, int64
use netcdf

integer :: err
integer(kind=int64) :: i
integer :: ncid

err = nf90_create("foo.nc", nf90_clobber, ncid)
i = 50
err = nf90_put_att(ncid, nf90_global, "att1", i)
if (err .ne. nf90_noerr) then
  write(error_unit, *) nf90_strerror(err)
  stop 1
endif
err = nf90_close(ncid)

end program main
```

**Comment by magnusuMET** [comment]
Could this be due to the default format of the file? CDF-1 does not support 8-byte integers anywhere

**Comment by menzel-gfdl** [comment]
I tried changing the second argument of `nf90_create` to `ior(nf90_clobber, nf90_netcdf4)` and `ior(nf90_clobber, nf90_64bit_offset)` and still get the same error.

**Comment by edwardhartnett** [comment]
OK, I am looking into this now.

If I run the following code, I get the error when attempting to put the att:

```
       int ncid;
       long long int i = 50;

      if (nc_create(FILE_NAME, NC_CLOBBER, &ncid)) ERR;
      if (nc_put_att_longlong(ncid, NC_GLOBAL, ATT_1, NC_INT64, 1, &i)) ERR;
      if (nc_close(ncid)) ERR;
```

This is correct. Since the format is the original netCDF classic format, then NC_INT64 is not available and NC_EBADTYPE should be returned, and it is.

When I instead add NC_CDF5 or NC_NETCDF4 to the create mode flag, the code works, as it should, since NC_INT64 is defined in those binary formats.

So far, so good.

But I think the problem is actually in netcdf-fortran. However, let's setting the C question first. Does anyone have any C code which they feel shows an error? I believe the C library is actually behaving properly.

I will check in my test changes, and then move on to netcdf-fortran to see if I can find the problem there.

**Comment by menzel-gfdl** [comment]
In the c version, however, `NC_CLOBBER|NC_64BIT_OFFSET` fails, but `NC_CLOBBER|NC_NETCDF4` doesn't fail.

**Comment by edwardhartnett** [comment]
NC_INT64 is also not available in NC_64BIT_OFFSET format.

Only NETCDF4 and CDF5 support the extended integer types. The NC_64BIT_OFFSET and the original classic format only support the original 6 data types, which do not include NC_INT64.

**Comment by menzel-gfdl** [comment]
Ok thanks.  And my mistake, `ior(nf90_clobber, nf90_netcdf4)` does not crash.  I don't think there is any issue, but wonder
why we didn't encounter this in earlier netcdf versions.

**Comment by edwardhartnett** [comment]
I believe this is an issue in netcdf-fortran. I am about to start testing there.

**Comment by edwardhartnett** [comment]
I have added an issue for this to netcdf-fortran: https://github.com/Unidata/netcdf-fortran/issues/277
