### ISSUE TITLE
Filename too long, causing 'make dist' issue on linux.

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#2077]
@DennisHeimbigner 

`make dist` is failing on Ubuntu 21.04 and Ubuntu 20.04 (ARM64).  When running make dist, the following is observed:

```
>netcdf-c-4.8.1.tar.gz
tar: netcdf-c-4.8.1/dap4_test/baselinethredds/GOES16_CONUS_20170821_020218_0.47_1km_33.3N_91.4W.nc4.thredds: file name is too long (max 99); not dumped
tar: Exiting with failure status due to previous errors
```

This causes an error in `make distcheck`.  `dap4_test/test_thredds.sh` fails due to the m issing `.thredds` file.  Is there a replacement we can use, perhaps, with a shorter file name?

**Comment by DennisHeimbigner** [comment]
Fixing this may be a problem because the name|
"GOES16_CONUS_20170821_020218_0.47_1km_33.3N_91.4W.nc4"
is built into the url used to get the content.
I would need to provide a way to alias the names in some way so
the baseline file has a shorter name.
However, one way to hack this is by renaming the file in baselinethredds
to a shorter name.
Then we add a BUILT_SOURCE clause to Makefile.am to rename/copy
the shorter name to the full name.

**Comment by WardF** [comment]
Thanks Dennis, I’ll take a crack at the latter approach in the morning.
