### ISSUE TITLE
support hdf5 1.12 api

### ISSUE THREAD

**Issue by gdkrmr** [Unidata/netcdf-c#2233]
Is there a reason why you require hdf5 1.12 to be built with the `--with-default-api-version=v18` flag? I am trying to compile netcdf-c on Manjaro and the default package just doesn't come with this flag.

**Comment by WardF** [comment]
It is required for compatibility reasons, currently, in order to generate files that can be read and distributed most broadly. There are many existing systems in place amongst our community that would be unable to read the files generated by the newer api.

**Comment by gdkrmr** [comment]
I just found out that there are the compatibility macros:
```
cmake -DCMAKE_C_FLAGS="-DH5_USE_18_API" ..
make -j16
```
works for me, maybe this should be in the documentation somewhere or maybe I just missed it in the documentation.

**Comment by Dave-Allured** [comment]
No.  This issue was fixed in **netcdf-c release 4.8.1**.  Please see PR #2044.

Best practice is to create an HDF5 build with a **universal API** that supports ALL HDF5 API versions in a single build.  That is what PR #2044 does.  That is what HDF5 source does by design, if you don't misdirect it.  That is /probably/ also what Manjaro did with their default HDF5 package.

API compatibility and **file format compatibility** are two completely independent things.  It is best to remember this distinction and not mix them.

There were one or more previous netCDF releases that did this wrong and displayed the `--with-default-api-version=v18` requirement.  That is what was fixed by this PR.

@gdkrmr, I suspect that the real problem is that you were trying to build an older netCDF release against the Manjaro default HDF5 library, probably one of the 1.12 versions.  Try again with netcdf-c 4.8.1, the latest release, and I think this error will go away.  Then you will not need to make a custom HDF5 build, either.  Let us know how it turns out.

Here  is the reference page for **HDF5 API compatibility**.  The relevant part for today is the very short section "Library Mapping Options" near the top of this page:
https://portal.hdfgroup.org/display/HDF5/API+Compatibility+Macros

**Comment by Dave-Allured** [comment]
@gdkrmr, I did not properly address your workaround `cmake -DCMAKE_C_FLAGS="-DH5_USE_18_API`.  On reflection I think that is probably a valid workaround **if** you are trying to install a down-level netcdf-c version such as 4.8.0.  I think the effect is that it forces the API requirements of that particular netcdf-c version to be correctly resolved.

The short answer is, you probably made a good netcdf-c build.  Upgrading to netcef-c 4.8.1 would be as good or better.

**Comment by gdkrmr** [comment]
Thanks for the response. I think it was my mistake. I was using an older local repository and I am pretty sure that that I did a `git pull` but maybe something went wrong or I just forgot. I deleted the local repository and cloned it again and now it works.
