### ISSUE TITLE
nczarr replaces double-quotes in attributes with single quotes

### ISSUE THREAD

**Issue by jim22k** [Unidata/netcdf-c#2506]
I don't know if this is specific to netcdf4-python or the C implementation, but when saving in nczarr format, every instance of a literal double-quote in an attribute string is replaced with a literal single-quote.

I am running netcdf4-python version 1.6.0 on a Mac, with python version 3.9.13.

Code to replicate:
```python
>>> import netCDF4 as nc
>>> nc.__version__
'1.6.0'
>>> def quick_test(filename):
...    ds = nc.Dataset(filename, 'w')
...    ds.setncattr('meta', """Hello "double" friend and 'single' friend""")
...    ds.close()
...    ds = nc.Dataset(filename, 'r')
...    print(ds.getncattr('meta'))
...    ds.close()
>>> quick_test('regular.nc')
Hello "double" friend and 'single' friend
>>> quick_test('file://thisisbuggy.zarr#mode=nczarr,file')
Hello 'double' friend and 'single' friend
```

**Comment by DennisHeimbigner** [comment]
It does not appear to be in the netcdf-c library. Attached is a C language program to test it out.
[tquote.c.txt](https://github.com/Unidata/netcdf-c/files/9580077/tquote.c.txt)

Assuming  my test program is correct, then my best guess is that the python wrapper for the netcdf-c library is` the culprit.

**Comment by dopplershift** [comment]
@jim22k What version of libnetcdf do you have installed? It looks like the culprit is in the `escape` function as of 4.8.1:

https://github.com/Unidata/netcdf-c/blob/cd6173f472b778fa0e558982c59f7183aa5b8e47/libdispatch/ncjson.c#L780-L804

It was erroneously replacing `"` with `'` there on line 793.

@DennisHeimbigner it looks like you already fixed this issue and it was released in 4.9.0. But yes, it was actually an issue with the C-library. :wink:

**Comment by DennisHeimbigner** [comment]
I stand corrected.

**Comment by jim22k** [comment]
Sure enough, I have libnetcdf 4.8.1. I'll upgrade to 4.9.0. Thanks!
