### ISSUE TITLE
NC_UNLIMITED in the wrong

### ISSUE THREAD

**Issue by barronh** [Unidata/netcdf-c#2514]
* NetCDF v4.8.1
* Linux, compilers various (gcc v4.8.5, intel 19.0), reproduciable with ncdump or netCDF4
* Below is the command necessary to reproduce the error:

ncdump -h https://snpp-omps.gesdisc.eosdis.nasa.gov/opendap/SNPP_OMPS_Level2/OMPS_NPP_NMNO2_L2.2/2022/162/OMPS-NPP_NMNO2-L2_2022m0611t193917_o55040_2022m0611t220125.h5

On a local copy of the same file 

ncdump -h /work/ROMO/satellite/OMPS/snpp-omps.gesdisc.eosdis.nasa.gov/data/SNPP_OMPS_Level2/OMPS_NPP_NMNO2_L2.2/2022/162/OMPS-NPP_NMNO2-L2_2022m0611t193917_o55040_2022m0611t220125.h5

I get a 

```
*** Error in `ncdump': malloc(): memory corruption: 0x0000000000955470 ***
```

I suspect this has to do with all the dimensions being passed as NC_UNLIMITED.

**Comment by WardF** [comment]
Are you able to run `h5dump` on the local copy of the file, out of curiosity?

**Comment by DennisHeimbigner** [comment]
Your url causes ncdump to attempt to read the data using the DAP2
protocol. The important thing to understand is that the netcdf-c library
interprets DAP2 to netcdf-3 (classic) and not to netcdf-4 (enhanced).
This means that the DAP2 meta-data  must conform to the netcdf-3 rules.
Among those rules is that there can only be one unlimited dimension and
it must occur as the first dimension of any variable that references it.
Your dataset violates that rule.

To see this, you need to see the actual DAP2 representation.
This representation of the meta-data consists of two parts: the .dds
which is the variable declarations and the .das which is the attribute
declarations.
You can obtain these using these commands:
>wget 'https://snpp-omps.gesdisc.eosdis.nasa.gov/opendap/SNPP_OMPS_Level2/OMPS_NPP_NMNO2_L2.2/2022/162/OMPS-NPP_NMNO2-L2_2022m0611t193917_o55040_2022m0611t220125.h5.das'

and
>wget 'https://snpp-omps.gesdisc.eosdis.nasa.gov/opendap/SNPP_OMPS_Level2/OMPS_NPP_NMNO2_L2.2/2022/162/OMPS-NPP_NMNO2-L2_2022m0611t193917_o55040_2022m0611t220125.h5.dds'

If you look at the end of the .das file, you will see this.
 ````
DODS_EXTRA {
        String Unlimited_Dimension "DimCorners";
    }
````
Then if you look at the .dds, you will see, for example, this.
````
 Float32 GeolocationData_LongitudeCorner[DimAlongTrack = 400][DimCrossTrack = 36][DimCorners = 4];
````
which as you can see has the unlimited dimension DimCorners as the
last dimension instead of the first.

**Comment by barronh** [comment]
@WardF - Yes, no error with h5dump. ‘ncdump -h’ works. I just get the error and the core dump. 

@DennisHeimbigner - your explanation of the opendap makes sense. Why does ncdump core dump the local file?

**Comment by DennisHeimbigner** [comment]
>  Why does ncdump core dump the local file?

I think that was fixed some time ago. Have you tried netcdf-c version 4.9.0?

**Comment by barronh** [comment]
Thanks-I will!
