### ISSUE TITLE
Can't find or link to the hdf5 library

### ISSUE THREAD

**Issue by MuzafarWani** [Unidata/netcdf-c#2565]
I am trying to install netcdf-c-4.9.0
I installed the prerequisites hdf5 and zlib but when I try to install netcdf it throws error
**checking for library containing H5Fflush... no**  
I am using the below command to install
CPPFLAGS='-I${hdf5dir}/include -I${zdir}/include ' LDFLAGS='-L${hdf5dir}/lib -L${zdir}/lib ' ./configure --prefix=/home/muzafar/Downloads/installs/netcdf
and hdf5dir,zdir, are rest to respective installation directories.
Also I have set the LD_LIBRARY_PATH to /home/muzafar/Downloads/installs/hdf5/lib:
I am attaching a confg.log
can you please let me know what is the issue with my installation.
[config.log](https://github.com/Unidata/netcdf-c/files/10121220/config.log)

**Comment by WardF** [comment]
What version of hdf5 are you using? Can you provide the libhdf5.settings file from your installation?

**Comment by MuzafarWani** [comment]
[libhdf5_settings.txt](https://github.com/Unidata/netcdf-c/files/10129513/libhdf5_settings.txt)
I am using **hdf5 version 1.12.2**

**Comment by WardF** [comment]
Thank you.  From the config.log file you provided, we can see that the environmental variables you're setting aren't being properly picked up:

````
AM_CFLAGS=''
AM_CPPFLAGS=''
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_DISTCHECK_CONFIGURE_FLAGS += --disable-valgrind
AM_DISTCHECK_CONFIGURE_FLAGS ?=
AM_LDFLAGS=''
AM_V='$(V)'
````

This is puzzling.  I also notice now that you're using single quotes, `'`, instead of double quotes `"`, when defining CPPFLAGS, etc.  Single quotes will prevent the expansion of environmental variables (like ${hdf5dir}).  Try replacing the single quotes with double quotes, and let us know what happens.

**Comment by WardF** [comment]
To illustrate the point above, consider the following example of single quotes vs. double quotes:

````
wfisher@shetland:~/Desktop/gitprojects/netcdf-c$ A=B echo '$A'
$A
wfisher@shetland:~/Desktop/gitprojects/netcdf-c$ A=B echo "$A"
B
wfisher@shetland:~/Desktop/gitprojects/netcdf-c$ 

````

**Comment by MuzafarWani** [comment]
@WardF Thank you it worked

**Comment by WardF** [comment]
Glad to hear it!
