### ISSUE TITLE
install netcdf-4.1.3 on Mac Intel OS13 (zsh)

### ISSUE THREAD

**Issue by Ilovecodinghaha** [Unidata/netcdf-c#2578]
Hi all, 

I followed [this](https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compilation_tutorial.php) to set netcdf library for WRF, but can't build netcdf. It seems `make` & `make install` doesn't work (checked `make` version, GNU Make 3.81). 

Hope I can get help from here. 
Thanks everyone.

[make.install.log](https://github.com/Unidata/netcdf-c/files/10357202/make.install.log)

**Comment by WardF** [comment]
Hi,  the log you attached says that the error is that the file system is read-only, so that would be the first thing you'll need to take care of.  You might contact the WRF maintainers to see if they can provide a guide for WRF using netCDF 4.1.3; it's quite old, and I have no idea if it will even compile on modern architecture/compilers without some modification.
