### ISSUE TITLE
Fails to build with doxygen 1.9.8 (Unexpected subsubsection command found inside section)

### ISSUE THREAD

**Issue by sebastic** [Unidata/netcdf-c#2746]
As reported in [Debian Bug #1051162](https://bugs.debian.org/1051162)
> While preparing to upload doxygen 1.9.8, I did a partial rebuild of packages that build-depend on it.
> More info here: https://salsa.debian.org/debian/doxygen/-/wikis/ratt_doxygen_1.9.8+ds-1_amd64-partial
>
> Of 510 packages I tried, 6 failed and one is netcdf-doc.
>
> The build error was:
> ```
> /<<PKGBUILDDIR>>/docs/dispatch.md:392: error: Unexpected subsubsection command found inside section! (warning treated as error, aborting now)
> make[3]: *** [docs/CMakeFiles/doc_all.dir/build.make:74: docs/CMakeFiles/doc_all] Error 1
> ```
> 
> I attach the full build log. 
> 
> [netcdf_1:4.9.2-1.xz](https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=1051162;filename=netcdf_1%3A4.9.2-1.xz;msg=5)

Treating warnings as errors seems unwise, this should resolve that:
```diff
diff --git a/docs/Doxyfile.in b/docs/Doxyfile.in
index ccfcd90fe..a6c3af393 100644
--- a/docs/Doxyfile.in
+++ b/docs/Doxyfile.in
@@ -777,7 +777,7 @@ WARN_NO_PARAMDOC       = YES
 # a warning is encountered.
 # The default value is: NO.
 
-WARN_AS_ERROR          = YES
+WARN_AS_ERROR          = NO
 
 # The WARN_FORMAT tag determines the format of the warning messages that doxygen
 # can produce. The string should contain the $file, $line, and $text tags, which
```

**Comment by edwardhartnett** [comment]
Treating warnings as errors in the documentation is indeed very wise!

The reason to do this is to ensure that no PR is merged which contains documentation warnings. Since the documentation build will break when there is a warning, this is detected in CI.

So this should not  be changed. INstead the warning should be fixed.

**Comment by WardF** [comment]
This should be fixed in the next release candidate; it is fixed in `main` right now.  When I say 'fixed', issues such as the one you've relayed should be fixed.  We also now invoke the doxygen update command before running `Doxygen` against the generated `Doxyfile`, so that tags which are not compatible with the local version of doxygen are removed automatically, instead of generating warnings-as-errors.
