### ISSUE TITLE
pnetcdf (still) not found during installation

### ISSUE THREAD

**Issue by VictorEijkhout** [Unidata/netcdf-c#2872]
Referring to previous ticket https://github.com/Unidata/netcdf-c/issues/2870. Thanks. 

I'm not finding instructions on how to specify the paths for pnetcdf in https://docs.unidata.ucar.edu/nug/current/getting_and_building_netcdf.html#netCDF-CMake

I put the `pnetcdf.pc` file on the `PKG_CONFIG_PATH`, but Cmake reports:
```
-- Cannot find PnetCDF library. Disabling PnetCDF support.
```

**Comment by VictorEijkhout** [comment]
Thanks. I think tinkering with `CMAKE_C_FLAGS` overrides some internal settings because I had to add quite a bit. Now my cmake line is:
```
cmake
-D CMAKE_INSTALL_PREFIX=/work2/00434/eijkhout/netcdf/installation-pnetcdf-4.9.2-stampede3-gcc13-impi                     
-D CMAKE_COLOR_DIAGNOSTICS=OFF                    
 -D CMAKE_VERBOSE_MAKEFILE=ON                     
-D BUILD_SHARED_LIBS=ON                     
-D ENABLE_PNETCDF=ON 
-D CMAKE_C_FLAGS='-I/work2/00434/eijkhout/parallelnetcdf/stuff/include -I -I/opt/apps/gcc13/impi21/phdf5/1.14.3/include -L/work2/00434/eijkhout/parallelnetcdf/stuff/lib -lpnetcdf' 
-D ENABLE_PARALLEL4=ON
-D ENABLE_PARALLEL_TESTS=OFF 
-D ENABLE_NETCDF_4=ON 
-D ENABLE_DAP=OFF                      
/work2/00434/eijkhout/netcdf/netcdf-4.9.2/
```
but in the end it works.

**Comment by WardF** [comment]
One option (that's unnecessary since you have found a fix that works), perhaps for the future, is to try -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} [additional flags]"; this way you'll include the previous flags as well as set the new ones.  Note that I'm making some assumptions about how the extant flags are being set, but it's possible this approach would work without overwriting existing flags.

I'm going to close out this issue since you have a solution, but if something else related arises, you can always comment on a 'closed' issue and I will reopen it if the issue isn't resolved.  Sorry for the premature closure of the previous issue :).

**Comment by VictorEijkhout** [comment]
Note my initial comment about pnetcdf having a `.pc` file. I think you should detect that, and save me from having to specify paths to begin with. I think pkg_config is a Good Thing.
