### ISSUE TITLE
Enhancement Request: Ability to use other MPI Launchers in tests

### ISSUE THREAD

**Issue by mathomp4** [Unidata/netcdf-c#302]
All,

This is just a Feature Request for changes to the parallel tests for netCDF. Namely, all the tests in netCDF seem to assume that mpiexec is available and will work. Sometimes, this isn't the case (well, it's usually there; it's the _will work_ that has issues). 

For example, with Intel MPI 5.1, mpiexec requires mpd to be booted, but mpiexec.hydra (symlinked to mpirun) is by far the preferred launcher for Intel MPI. If you don't go into the tests and change to mpirun, the tests all fail if mpdboot isn't on. (I think in Intel MPI 2017, they just removed the mpd version, so the test might work again!). Likewise, SGI MPT prefers mpiexec_mpt, Open MPI prefers mpirun, and MVAPICH2 prefers mpirun_rsh.

So, I was wondering if it'd be possible to have the mpirun command be something that, say, configure could pass in (or environment variable, or whatever cmake does). I suppose defaulting to mpiexec is a good default since, I think, the MPI Standard says it is recommended (though not required).

Obviously, if netCDF could detect the type of MPI stack, that'd be ideal, but just allowing one to set it would be fine.

Thanks,
Matt

PS: Note that "netCDF" here means netCDF-C and netCDF-Fortran. I just started here because this is the Big Cheese™. If an acceptable solution can be created for netCDF-C, I could then file an issue over at [Unidata/netcdf-fortran](https://github.com/Unidata/netcdf-fortran)

**Comment by WardF** [comment]
I have nothing to say against the proposed enhancement; the issue comes from the lack of in-house resources.  I can wire something like this in as an option, e.g. a way to set the environmental variable for the mpi executable, but we do not have a broad selection of parallel systems to choose from, so testing would be limited.  

I will mark this as under consideration and will add it to the best of our ability here, and will document it as such; I will implement whatever solution is made here in netCDF-Fortran as well.  I'll also add that a pull request with this functionality would be quite welcome :).  Otherwise, we'll address it when we're able to.

Thanks for the background information, however; I was not aware of any of these issues, so it is great to know.

**Comment by edhartnett** [comment]
I agree that this would be a useful enhancement.

FWIW a workaround is to change the contents of nc_test4/run_par_test.sh.

**Comment by mathomp4** [comment]
I know I could hack a way in using pure Make (fun with $(shell)!) but it's autotools...it's always autotools... Maybe it's time to learn!

> FWIW a workaround is to change the contents of nc_test4/run_par_test.sh.

Indeed, my usual method is to convert all the mpiexec to mpirun. The odd one comes with MPT. It's mpirun is an odd one to say the least. Luckily netcdf-c/fortran don't do anything fancy and/or interact with resource managers

**Comment by edhartnett** [comment]
I also ran into this need when installing netcdf on a supercomputer.

I have fixed this so that the --with-mpiexec= argument to configure allows the user to set the command that will be used to launch MPI programs. The default value remains mpiexec.

This is on WDC branch ejh_change_mpiexec. I will put up a PR presently.
