### ISSUE TITLE
argument fill_valuep in nc_inq_var_fill

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#327]
The argument `fill_valuep` is a pointer of void type defined in `nc_inq_var_fill`.
`int nc_inq_var_fill (int ncid, int varid, int *no_fill, void *fill_valuep);`

When trying to get the default fill values, this API leads to `nc4_get_default_fill_value` in line 169 of file nc4hdf.c. I can see type-casting of `fill_valuep` before assigning a pre-defined fill constant to it. This could be erroneous, as users may, for example, use a double in `fill_valuep` to inquire `NC_FILL_SHORT`. The type-casting will treat `fill_valuep` as a pointer of size 2 bytes. Below is a test program that can show the problem.
```
#include <stdio.h>
#include <stdlib.h>
#include <netcdf.h>

#define ERR {if(err!=NC_NOERR){printf("Error at line=%d: %s\n", __LINE__, nc_strerror(err));exit(1);}}

int main(int argc, char* argv[])
{
    int err, cmode, ncid, varid1, varid2;
    double fillv=0.0;

    cmode = NC_NETCDF4 | NC_CLOBBER;
    err = nc_create("testfile.nc", cmode, &ncid); ERR
    err = nc_def_var(ncid, "v1", NC_BYTE, 0, NULL, &varid1); ERR
    err = nc_def_var(ncid, "v2", NC_SHORT, 0, NULL, &varid2); ERR
    err = nc_enddef(ncid); ERR

    err = nc_inq_var_fill(ncid, varid1, NULL, &fillv); ERR
    printf("fill value of NC_BYTE  = %g\n",fillv);
    err = nc_inq_var_fill(ncid, varid2, NULL, &fillv); ERR
    printf("fill value of NC_SHORT = %g\n",fillv);
    err = nc_close(ncid); ERR
    return 0;
}
```
The output from screen is given below.
```
fill value of NC_BYTE  = 6.37345e-322
fill value of NC_SHORT = 1.619e-319
```
One possible solution is to change the data type of `fill_valuep` to double or
limit users to use a buffer of the same size as the variable data type.

**Comment by edhartnett** [comment]
We cannot limit users to type double. This function needs to work for user-defined types as well as atomic types, so we don't know a maximum type size.

We cannot limit users to use buffer of same size because we have no way of know what size the buffer is, we just get a pointer. It us up to the user to have a buffer of the correct size for the type.

@WardF I suggest this ticket be closed.

**Comment by wkliao** [comment]
I understand there is no way to tell whether the memory space pointed to the user buffer argument is sufficiently large for the variable's external data type. My concern is when the user buffer is too small, calling nc_inq_var_fill can corrupt the memory space following the user buffer, according to the way function nc4_get_default_fill_value assigns the fill value to the user buffer.

At least, the user guide can explicitly remind users the possible problem if user buffer type does not match or smaller than the variable external type.

**Comment by edhartnett** [comment]
I have added the documentation as you suggest. PR up now.

**Comment by DennisHeimbigner** [comment]
The memory overwrite problem is common in the netcdf-c API because it relies on the user
passing in the memory for such things as nc_get_var or get_attr. It might be nice to have a function
that given a typeid allocates enough memory to hold 1 or more instances of that type.

**Comment by DennisHeimbigner** [comment]
As you know, the C library API has changed over time to provide
alternate functions that are safer against memory overflow.
Perhaps it is time to do the same for the netcdf-C API.
We could provide alternates for things like nc_inq_var_fill
and nc_get_varX where the netcdf-c library allocates the memory
and returns it to the user instead of having the user pass in the memory.
