### ISSUE TITLE
Is nc_inq_var_fill() returning the correct answer for parameter no_fill for classic file?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#379]
I run this code to create a netcdf file with 1 dim, 1 var, and I write 1 value:

```
#define NDIM1 1
#define DIM_LEN 4
#define DIM_NAME "my_dim"
#define VAR_NAME "my_var"

       int ncid;
        int dimid;
        int varid;
        int cmode = 0;
        char testfile[] = "test.nc";
        size_t index = 2;
        int test_val = 42;
        int no_fill;
        int ret;
        
        if ((ret = nc_create(testfile, cmode, &ncid)))
            return ret;
        if ((ret = nc_def_dim(ncid, DIM_NAME, DIM_LEN, &dimid)))
            return ret;
        if ((ret = nc_def_var(ncid, VAR_NAME, NC_INT, NDIM1, &dimid, &varid)))
            return ret;
        if ((ret = nc_enddef(ncid)))
            return ret;
        if ((ret = nc_put_var1_int(ncid, varid, &index, &test_val)))
            return ret;
        if ((ret = nc_inq_var_fill(ncid, varid, &no_fill, NULL)))
            return ret;
        printf("in netcdf test no_fill = %d\n", no_fill);
        if ((ret = nc_close(ncid)))
            return ret;

```
As expected I get a file like this:

```
netcdf test {
dimensions:
	my_dim = 4 ;
variables:
	int my_var(my_dim) ;
data:

 my_var = _, _, 42, _ ;
}

```

But my print statement is telling me that no_fill is set for this variable:

`in netcdf test no_fill = 1
`

Since I have not changed the fill mode, I expect this value to be 0, indicating that fill mode is on, which is the default. And indeed it does seem to be on. But nc_inq_var_fill is telling me that it is not.

Am I missing something?

(Note I do get the correct answer when I change cmode to NC_NETCDF4.)

**Comment by WardF** [comment]
You don't seem to be missing anything; I'll take a look at this.

**Comment by wkliao** [comment]
I guess nc_inq_var_fill() was initially developed for NetCDF-4 files only (based on an older netCDF C Interface Guide [4.1.3 doc for nc_inq_var_fill](http://www.unidata.ucar.edu/software/netcdf/documentation/historic/netcdf-c/nc_005finq_005fvar_005ffill.html)). Look like the latest C Interface Guide no longer requires netCDF-4 ([latest doc for nc_inq_var_fill](http://www.unidata.ucar.edu/software/netcdf/docs/group__variables.html#gaf4a2635933f4b58a5cc2025e4e2e120f)). I also see no reason not to make it available for classic files.

For classic files, I traced the cause to [line 202 of file libsrc/nc3dispatch.c](https://github.com/Unidata/netcdf-c/blob/master/libsrc/nc3dispatch.c#L202) which always sets the returned fill mode to 1. However, the fix may not be simple, because per variable fill mode is not saved in [NC_var](https://github.com/Unidata/netcdf-c/blob/master/include/nc3internal.h#L176), a C struct defined in nc3internal.h that stores a variable's metadata.

Similar setting is used in PnetCDF dispatcher, [line 1163 of libsrcp/ncpdispatch.c](https://github.com/Unidata/netcdf-c/blob/master/libsrcp/ncpdispatch.c#L1163). But because PnetCDF has implemented API ncmpi_inq_var_fill since 1.6.1, the fix can be just to change line 1163 to the followings.
```
status = ncmpi_inq_var_fill(nc->int_ncid, varid, no_fill, fill_valuep);
if (status != NC_NOERR) return status;
```

**Comment by edhartnett** [comment]
WRT the per-variable fill mode in classic files, I understand that it is not controllable. 

But the no_fill value returned by nc_inq_var_fill() should reflect the correct fill setting for the file. So if it is not changed for the file, I would expect no_fill == 0 for any variable in the file.

**Comment by edhartnett** [comment]
I just tested this, and, as I expected, since @wkliao's changes, this now works properly. I have a test that confirms this, I will put up a PR and then this ticket can be closed.
