### ISSUE TITLE
Can not nccopy a file with a `_Netcdf4Dimid` attribute

### ISSUE THREAD

**Issue by kwilcox** [Unidata/netcdf-c#423]
### Environment Information

netCDF library version 4.4.1.1 of Dec 25 2016 19:06:13

* What platform are you using? (please provide specific distribution/version in summary)
  * [x] Linux
* 32 and/or 64 bit?
  * [x] 64-bit
* What build system are you using?
  * [x] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [x] Yes (please attach to this issue, thank you!)

### Summary of Issue

A file or DAP endpoint with a variable attribute of `_Netcdf4Dimid` will fail to download/convert to netCDF4. Originally discovered/reported here https://github.com/nco/nco/issues/57.

### Steps to reproduce the behavior

```
$ nccopy -7 -v z http://oceanmodeling.pmc.ucsc.edu:8080/thredds/dodsC/ccsra_2016a_phys_agg_zlevs/fmrc/CCSRA_2016a_Phys_ROMS_z-level_\(depth\)_Aggregation_best.ncd out.nc
NetCDF: String match to name in use
Location: file /feedstock_root/build_artefacts/recipe_root_1482692731718/work/netcdf-c-4.4.1.1/ncdump/nccopy.c; line 788
```

**Comment by DennisHeimbigner** [comment]
The Thredds server you are accessing is very old: 4.2.9.
The current is 4.6.10.

Since _Netcdf4Dimid is a reserved netcdf name, it should not be
possible to access it thru the netcdf API. But the Thredds
server by default uses the HDF5 Iosp to read the netcdf-4 file
and it is probable that the version of the Iosp the server is
using is not suppressing reserved attributes.  I did a quick
check, and the latest thredds 4.6 server does properly suppress
_Netcdf4Dimid.

The only solutions I can think of are:
1. Get the server upgraded.
2. hack the netcdf-c library to do the suppression
3. hack nco to do the suppression.

I am not happy with #2 and I am sure Charlie would not be happy with #3.
Is a server upgrade at all feasible?

=Dennis Heimbigner
 Unidata

**Comment by kwilcox** [comment]
I'm also against fixing this in `netcdf-c` or `nco`. I don't control the THREDDS server but I can reach out and see if they are willing to upgrade. I have a work-around in place to remove the attribute so it plays nicely with the rest of the workflow. Feel free to close!
