### ISSUE TITLE
Attempting to open DAP dataset creates a temporary file which is not removed

### ISSUE THREAD

**Issue by djkirkham** [Unidata/netcdf-c#435]
### Environment Information
  * Linux
  * 64-bit
  * cmake

### Summary of Issue

Attempting to open a remote dataset via a URL creates a folder in `/tmp` with a name of the form `oc.*` and a single empty file inside. This happens whether or not the URL refers to an actual dataset. I see the behaviour in version 4.4.1 but not 4.3.1.

In our system, which is opening a large number of Datasets, this is causing the filesystem to run out of inodes.

### Steps to reproduce the behavior

```
$ ncdump http://some.url
```
```l
$ ls /tmp/oc.*
```

The behaviour also occurs using the Python `netCDF4.Dataset`

**Comment by WardF** [comment]
@DennisHeimbigner Is this behavior explained by the C library?  Or is this something we should tag the python devs on?

**Comment by DennisHeimbigner** [comment]
Depends on what version of netcdf-c is being used. Before we added diskless support,
the opendap code did create a temporary file. After diskless was added, that temporary
file was created using that mechanism and so no file appeared in the file system.
I do not recall off hand, but it may be the case that if diskless is not supported/enabled
when netcdf-c is built, then the library reverts to the old behavior of creating a temporary file.
So, if we can see the output or the contents of libnetcdf.settings, we may be able to figure out
if the netcdf-c library is creating that temp file.
One other thing to do is to delete it, run the program again and see if it comes back
and if the creation date indicates that it was created during the execution of the program.

**Comment by djkirkham** [comment]
@DennisHeimbigner I'm pretty certain the file is being created by the call to netcdf. It only appears after the call to either ncdump, or netCDF4.Dataset in Python. I don't use libnetcdf directly so I can't make a more direct call, but since it's created by ncdump, I assume it's the C code creating it and not the Python module.

I am able to create a diskless Dataset using the Python module, so it seems diskless is enabled. I've tried setting diskless=False when opening a DAP dataset using the Python module but the temp file is still created.

**Comment by DennisHeimbigner** [comment]
The situation is described tersely in netcdf-c/docs/auth.html#REDIR
Basically, when a url is used that requires redirection, a physical
cookiejar drectoryis required to exist in the file system in order for this to work.
Since it was difficult to figure out when redirection was
being used (it was internal to libcurl) I needed to be prepared for that
eventuality. The result was that I always created a cookiejar directory if one
was not specified in the rc file.
My big error was not reclaiming that cookiejar file on close(). Ideally, I would
like to be able to create the cookiejar file on the fly just before a redirection
occurs, but that requires use of CURLINFO_REDIRECT_URL and that requires
(AFAIK) duplicating the existing curl redirect handling code: something I would
rather not do.

So, I at the very least make sure to clean up the cookiejar directory is removed
at nc_close() time. Beyond that I am not sure what else I can do.

**Comment by djkirkham** [comment]
Removing the directory should resolve the issue on our system so I'm in favour of that change going in at least.

**Comment by djkirkham** [comment]
> I always created a cookiejar directory if one
was not specified in the rc file.

So I can prevent the the temp file being created by specfying a file via HTTP.COOKIEJAR in the rc file?

**Comment by DennisHeimbigner** [comment]
Yes, that should work.

**Comment by DennisHeimbigner** [comment]
Fixed by pull request https://github.com/Unidata/netcdf-c/pull/436
