### ISSUE TITLE
Improve documentation for dispatch layer

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#493]
docs/internal.dox needs to be converted to markdown, and referenced from the programming notes section. There is also a document dispatch.dox that needs to be folded in.

**Comment by WardF** [comment]
`pandoc` is great for converting html to markdown; I've used it to convert the rendered version of .dox files to markdown.  I can handle that.  I've been slowly reorganizing the documentation (and it has slowed further since Russ retired), so feel free to fold in the PIO stuff and we'll get it slotted in in the right place :)

**Comment by edhartnett** [comment]
Actually there is great documentation if I build with --enable-internal-docs, so I am happy. ;-)

I will let you know if I find anything wrong as I go through the PIO process. Meanwhile I will close this ticket.

**Comment by WardF** [comment]
Sounds good! FWIW there's also a doxygen file, `docs/Doxyfile.developer`, that generates **robust** documentation.  It is built by running doxygen against it directly, e.g. 

    $ doxygen docs/Doxyfile.developer && open html/index.html

**Comment by DennisHeimbigner** [comment]
The dispatch documentation has a number of errors/misstatements. I will
undertake to update it.

**Comment by DennisHeimbigner** [comment]
Pull request https://github.com/Unidata/netcdf-c/pull/497
updates the dispatch table documentation to make it more
accurate.
