### ISSUE TITLE
Proposed new version of _NCProperties

### ISSUE THREAD

**Issue by DennisHeimbigner** [Unidata/netcdf-c#592]
Here is the proposed format(s) for the_NCProperties provenance attribute. Version 1 is as before,
but version=2 is new. One thing missing is to allow the insertion of non-library related attributes:
things such as e.g. ./configure flags.

Proposed Format for _NCProperties Attribute:

This attribute is persistent in the file, but hidden. IT can be used using, for example, "ncdump -h".

This attribute is inserted in the file at creation time and is never modified after that point. There are now multiple versions of the format of this attribute. The type of this attribute is currently always NC_CHAR.

For all versions (to date), the format is: name=value|name=value ..., where occurrences of '|' in the name or value are disallowed. The value part may be elided. For all versions, the first name=value must be as follows.
        version=1|2 The current format version for the _NCProperties file.

Version 1 specifies the following specific name=value pairs.
* netcdflibversion=... --The version of the netcdf library used to create the file. The value is, for example, 4.4.1-rc1-development or 4.4.1.
* hdf5libversion=... -- The version of the HDF5 library used to create the file. The value is, for example, 1.8.16 or 1.10.0.

Version 2 specifies no specific names, but the first name is the name of the main library that produced this file and the value is the version string. For a netcdf-c produced file, for example, this would be something like "netcdf=4.5.0".

After the main library, supporting libraries are listed in no specific order. Each such support library has the form "<canonical library name>=<version>".

Determining the canonical name is left unspecified here, which means that conflicts may occur, so be warned. Typically, the controlling organization specifies its library using some format like "<libname>-<version>" or "<libname><version>" or "<libname>.<version>". So as a rule, the "<libname>" part should be used as the canonical name and the "<version>" part as the version string. For example, given "hdf5-1.8.17", it should appear in _NCProperties in the form "hdf5=1.8.17"

**Comment by Dave-Allured** [comment]
I support this proposal.  I particularly like the shortened canonical names, and your consideration of alternative libraries.

Here are a few suggestions.  Please add these only if you like my reasoning.

1.  Version numbering is important for some things, but not for the _NCProperties attribute itself.  I don't think there are any automatons that care.  The name/value pair for _NCProperties version should be dropped completely, if for no better reason than to improve human readability.

2.  Move toward the widely utilized CSV syntax.  Use comma "," for the primary delimiter, not vertical line "|".  IMO this improves human readability and avoids possible confusion of vertical line with lowercase "L" and numeral "1".

3.  Allow certain white space between, but not within, name/value pairs; in addition to the primary delimiter.  In particular, spaces and newlines may be desirable in the future.

4.  Looking ahead, I would prefer that possible configure flags would be listed in newly invented provenance attributes, rather than extending the _NCProperties attribute.

**Comment by shoyer** [comment]
Yes, this would be valuable for alternative libraries that write netCDF files (e.g., scipy and h5netcdf).

I am concerned about separately indicating:
1. The version of the main library writing the file.
2. The version of the netCDF-C library that can read this file, or equivalently the exact version of the netCDF file format itself.

For netCDF-C, these versions will always coincide. But another library might write a netCDF file only readable with a certain version of netCDF-C (e.g., making use of a new compression filter). It would be nice to have a way of indicating this in the metadata.

**Comment by Dave-Allured** [comment]
Was completed by PR #1124.  Please close this issue.

@shoyer if your related concerns are not resolved, please start a new issue.
