### ISSUE TITLE
netcdf 4.5.0 creates files with bad fill values

### ISSUE THREAD

**Issue by jedwards4b** [Unidata/netcdf-c#730]
[testfile45.nc.gz](https://github.com/Unidata/netcdf-c/files/1577292/testfile45.nc.gz)
[testfile4411.nc.gz](https://github.com/Unidata/netcdf-c/files/1577293/testfile4411.nc.gz)

> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [X ] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [X] 64-bit
* What build system are you using?   (not sure - build provided by cisl)
  * [ ] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [X] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue
netcdf 4.5.0 seems to provide a default fillvalue which is incorrect, I found this to be the case for both int and float, the testcase is for int only

### Steps to reproduce the behavior

```
#include <stdio.h>
#include <netcdf.h>

int main()
{
    int ncid, vid;
    int ierr;
    void *fillvalue;

    ierr = nc_open("testfile45.nc", 0, &ncid);

    ierr = nc_inq_var_fill(ncid, 0, NULL, fillvalue);

    printf("found fillvalue %d expected %d\n",*((int *) fillvalue), NC_FILL_INT);

    ierr = nc_open("testfile4411.nc", 0, &ncid);

    ierr = nc_inq_var_fill(ncid, 0, NULL, fillvalue);

    printf("found fillvalue %d expected %d\n",*((int *) fillvalue), NC_FILL_INT);
}
```
The two test files are attached.   The result of the test program is
 ./a.out
found fillvalue 1 expected -2147483647
found fillvalue -2147483647 expected -2147483647

**Comment by wkliao** [comment]
Just a side note, the test program is buggy. Variable fillvalue should be defined of type int, instead of a pointer. A physical  memory space is required for nc_inq_var_fill() to store the inquired fill value.

One interesting observation is that ncdump 4.5.0 command shows variable 0 "Billy-Bob" does not have _FillValue attribute defined in either file but nc_inq_var_fill() reports the variable's fill mode is OFF in file testfile45.nc and ON in testfile4411.nc. I thought NetCDF's default is ON for all variables.

In addition, in the implementation of nc_inq_var_fill() in file libsrc4/nc4var.c
https://github.com/Unidata/netcdf-c/blob/0f7118107ee33eaab6c7e9a2f825204bf5a132ed/libsrc4/nc4var.c#L876
argument fill_valuep will not be set to the fill attribute value if the variable's fill mode is OFF. This does not sound right. A variable can have attribute _FillValue defined but its fill mode turned OFF, because a variable's fill mode is set by nc_set_fill() or nc_def_var_fill(), not attribute _FillValue. NetCDF should not prohibit the inquiry API from getting the fill value when fill mode is OFF.

**Comment by edhartnett** [comment]
@jedwards4b I believe this bug is now fixed in the master branch. I have a similar test on a branch of master which passes. That is, the correct fill values are used.

@wkliao when fill mode is off, a fill value is not returned because there is no fill value in effect. There may be a _FillValue attribute, but it is not operating as a fill value. Anyway, that was my reasoning. If others think that's confusing, I would be happy to make the change and just return the fill value that would be used if fill mode were on. Anyone else have an opinion?

**Comment by wkliao** [comment]
I am thinking a case when users would like to check the fill value when the mode is off to decide whether to use a different value before turning it back on.

**Comment by edhartnett** [comment]
Wasn't this in the 4.6.0 release?

**Comment by WardF** [comment]
Should be; closing out unless I hear differently.
