### ISSUE TITLE
If name hashes match, strings must also match, correct?

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#751]
In various places in the code, to compare names of things (like a dim and a var), we look at the hash. We also compare the name strings, as in this code from NC4_def_var():

`dim->hash == var->hash && !strcmp(dim->name, norm_name)`

Just to confirm my understanding, if the hash is the same, then the strings will also be the same. Is that correct? Seems like we should assert the second condition instead of testing it every time.

**Comment by gdsjaar** [comment]
No. It is possible for two or more names to have the same hash.   Rare but possible.

.. Greg

Sent from my iPad

On Dec 29, 2017, at 14:59, Ed Hartnett <notifications@github.com<mailto:notifications@github.com>> wrote:


In various places in the code, to compare names of things (like a dim and a var), we look at the hash. We also compare the name strings, as in this code from NC4_def_var():

dim->hash == var->hash && strcmp(dim->name, norm_name)

Have the same hash.  Just to confirm my understanding, if the hash is the same, then the strings will also be the same. Is that correct? Seems like we should assert the second condition instead of testing it every time.

-

**Comment by edhartnett** [comment]
Can you give me an example?

**Comment by WardF** [comment]
Hash map collisions are rare but cannot be guaranteed not to happen; I think it is worth checking, it would be a difficult bug to track down after the fact.

**Comment by edhartnett** [comment]
My starting point is that I want the greatest possible test coverage, and this is a currently uncovered test case.

As I fill in test coverage for the code in nc4var.c I am finding small bugs and fixing them. These are bugs that could have tripped up a user and caused work for users and the netCDF team. So it is certainly worth tracking them all down.

If we can find two different strings that give the same hash, I can add some tests and make sure we check for both the hash and the strcmp everywhere.

**Comment by DennisHeimbigner** [comment]
it i/ effectively impossible to construct a hash collision without using a large amount of compute power. If you really want to test this then you should create a fake hash function that
for example produces the same hash for all strings.
But you should know that I have a branch waiting that will completely change how hashing is used
in order to improve lookup times. So your test may be useful but the underlying code base is going to change a lot.

**Comment by DennisHeimbigner** [comment]
BTW how is the pio work progressing?

**Comment by edhartnett** [comment]
I will wait to add any tests of this until you are done.

PIO is fine but I am trying to solve rename problems before getting back to it...

**Comment by edhartnett** [comment]
I will close this ticket and circle back around to this after @DennisHeimbigner finished his hash work.
