### ISSUE TITLE
For classic file, nc_def_dim() returns 0 even when given an incorrect ncid

### ISSUE THREAD

**Issue by edhartnett** [Unidata/netcdf-c#791]
I am tightening up testing of nc4dim.c, the netCDF-4 dimension code.

But I accidentally discovered an odd bug in the classic code. Here's some code from tst_dims.c:

```
      /* Create a netcdf-3 file with one dim. */
      if (nc_create(FILE_NAME, 0, &ncid)) ERR;

      /* These will not work. */
      if (nc_def_dim(ncid + TEST_VAL_42, LAT_NAME, LAT_LEN, &dimid) != NC_EBADID) ERR;

```
(TEST_VAL_42 = 42).

This fails because the nc_def_dim() returns 0, even though it has been given an incorrect ncid. Not sure what is going on here, but I'm going to continue with testing the nc4dim.c code, and circle back to this oddity later.

**Comment by wkliao** [comment]
I believe this is a bug, affecting all versions 4.3.0 and after..
Starting 4.3.0, the value of ncid has been changed to a multiple of 65536.
When checking whether ncid is valid or not, function find_in_NCList simply
divides the user supplied ncid by 65536. Because ncid is of type int, the
division rounds down to the floor value. This bug can be serious for
applications using 4.3.0 and after, as a bad ncid can be pointed to a good
file already opened.

Below changes should fix it.  It adds a check for whether ncid is a multiple of 65536. 
```
 diff --git a/libdispatch/nclistmgr.c b/libdispatch/nclistmgr.c
 index 13679f0..e366959 100644
 --- a/libdispatch/nclistmgr.c
 +++ b/libdispatch/nclistmgr.c
 @@ -85,6 +85,7 @@ NC *
  find_in_NCList(int ext_ncid)
  {
     NC* f = NULL;
 +   if (ext_ncid % (1<<ID_SHIFT)) return NULL;
     unsigned int ncid = ((unsigned int)ext_ncid) >> ID_SHIFT;
     if(numfiles > 0 && nc_filelist != NULL && ncid < NCFILELISTLENGTH)
         f = nc_filelist[ncid];
```

**Comment by edhartnett** [comment]
The reason this is happening is that the last two bytes of the ncid are referring to the group.

Since classic files have no group, they should all have 0 for the last two bytes.

I don't believe that a bad id can point to a (different) good file. Since the last two bytes are simply ignored, anything from ncid to ncid + NC_MAX_SHORT would be the same as just ncid.

So I believe that this is a pretty minor bug. But it would be nice to fix it.

**Comment by wkliao** [comment]
In your code example, the bad ID is 65536+42, which is rounded down to 65536, a valid ncid for an already opened file. No error will ever be reported.

**Comment by gsjaardema** [comment]
But that ID is referring to group 42 of the file with nCID 65536 so it should be valid.

**Comment by wkliao** [comment]
That code example creates a classic NetCDF file, not NetCDF-4 file.
This issue only applies to classic files.
So, my fix also needs another check for whether the file is classic or not.

**Comment by DennisHeimbigner** [comment]
You better check the code carefully. There is no intrinsic requirement that
netcdf-3 ncid's need to be shifted since they have not group.

There may be another complication. I have a memory of Russ wanting to
treat the ncid as an unsigned int internally so that we could have 2**16 -1
open files. If I am correct, then the "division" by 65536 needs to be ncid >>> 16
as opposed to ncid >> 16

**Comment by gsjaardema** [comment]
Not sure what is meant by "implict requirement", but based on the code, there is a requirement that all non-group ncids are shifted -- `add_to_NCList` This may not be a technical or explicit requirement, but it is a "coded requirement" at the current time.

I think you may be doing too much java programming ... `>>>` is not C or C++. Operator for shifting signed or unsigned int is the same although right shift of negative signed integer is implementation defined.

**Comment by DennisHeimbigner** [comment]
Yes, instead of >>>, one would need to mask out the top 16 bit after shifing.
The controlling document here is the netcdf-3 standard.

**Comment by wkliao** [comment]
I revised the patch in #804 by adding a check for a classic NetCDF-3 file.

**Comment by edhartnett** [comment]
This fix and test have been merged. Thanks @wkliao!
